<a href="https://colab.research.google.com/github/xinleimiao/combine-the-similarity-of-text-by-TEI/blob/main/mathod1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


txt1 = np.array([[1,2,3,4,5,6,7,8,9],
                 [1,2,3,0,5,6,7,8,9],
                 [1,0,3,4,5,6,7,8,9],
                 [0,2,3,4,5,0,7,8,9],
                 [0,0,0,0,5,6,0,8,0],
                 [0,2,3,4,0,6,7,0,9]]);
txt2 = np.array([[0,2,3,4,5,6,7,8,9],
                 [1,2,3,0,5,6,7,8,9],
                 [1,0,3,4,5,6,7,8,9],
                 [0,2,3,4,5,0,7,8,9],
                 [0,0,0,0,5,6,0,8,0],
                 [0,2,3,4,0,6,7,0,9]]);

# # According to the example text format stores the corresponding bit whether the character exists.
# cmPr1 = np.zeros((6, 10), dtype = int);
# cmPr2 = np.zeros((6, 10), dtype = int);

# smLr12 = np.zeros((6, 10), dtype = int);

# Iterates through the text, specifying that the two text lines have 
# the same number of rows. If there is a space (that is, no character,which is "0" in temp), 
# add the number 1 to the reference array, and if there is a character, 
# add the number 0 to the reference array.

def sm_unsm(txt1,txt2):
  # According to the example text format stores the corresponding bit whether the character exists.
  cmPr1 = np.zeros((6, 9), dtype = int);
  cmPr2 = np.zeros((6, 9), dtype = int);

  smLr12 = np.zeros((6, 9), dtype = int);
  for i in range(len(txt1)):
    for j in range(len(txt1[i])):
      if (txt1[i][j] == 0):
        cmPr1[i][j] = 1;
      else:
        cmPr1[i][j] = 0;
  print(cmPr1);
  


  for n in range(len(txt2)):
    for m in range(len(txt2[n])):
      if (txt2[n][m] == 0):
        cmPr2[n][m] = 1;
      else:
        cmPr2[n][m] = 0;
  print(cmPr2);


# Compare the similarity of two contrast arrays. By bit comparison, 
# if both bits are 0 or 2, it is judged that the bits are similar, 
# and the same variable is added by one. If the values at the same position 
# in two arrays do not add up to 0 or 2, 
# the bits are determined to be dissimilar. The final similarity rate 
# is obtained by dividing the number of similar digits by the total number of digits.

  same = 0;
  uNsame = 0;
  for x in range(len(cmPr1)):
    for y in range(len(cmPr1[x])):
      smLr12[x][y] = cmPr1[x][y] + cmPr2[x][y];
      if (smLr12[x][y] == 0 or smLr12[x][y] == 2):
        same = same+1;
      else:
        uNsame = uNsame+1;
    rate_same = same/54; 
                      #  The similarity ratio is equal to the total number of 
  #                      similar elements divided by the total number of characters (including Spaces) 
  #                      in the text (that is, rows by columns).
  print(rate_same);

sm_unsm(txt1,txt2);








[[0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 1 0 0 0]
 [1 1 1 1 0 0 1 0 1]
 [1 0 0 0 1 0 0 1 0]]
[[1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 1 0 0 0]
 [1 1 1 1 0 0 1 0 1]
 [1 0 0 0 1 0 0 1 0]]
0.9814814814814815


In [ ]:
()