<a href="https://colab.research.google.com/github/xinleimiao/combine-the-similarity-of-text-by-TEI/blob/main/mathod2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# path = './io.txt';
# txt1 = open(path,'r',encoding='utf-8');
# txt2 = open(path,'r',encoding='utf-8');

txt1=['one day\n','   another day  \n'];
txt2=['   one day\n','another   day  \n'];

a1 = [];
a2 = [];

def sm_unsm2(txt):
  # T1 = txt1.readlines();
  # T2 = txt2.readlines();
  # T1_lines_num = len(T1);
  # T2_lines_num = len(T2);
  up_line_head=np.zeros(shape=(len(txt),1));
  up_line_tail=np.zeros(shape=(len(txt),1));
  # low_line_head=np.zeros(shape=(len(txt1),1));
  # low_line_tail=np.zeros(shape=(len(txt1),1));
  # print(len(txt[1]));
  n=0;
  for i in range(len(txt)):
    for l in txt[i]:
      if (l == ' '):
        n=n+1;
      else:
        up_line_head[i]=n;
        n=0;
        break;
  print(up_line_head);

  # for j in range(len(txt1)):
  #   for l in txt1[j]:
  #     if (l == ' '):
  #       n=n+1;
  #     else:
  #       low_line_head[j]=n;
  #       n=0;
  #       break;
  # print(low_line_head);

  for x in range(len(txt)):
    n = (len(txt[x])-2);
    for a1 in range(len(txt[x])):
      if (txt[x][n] == ' '):
        n=n-1;
      else:
        up_line_tail[x]=n;
        n=0;
        break;
  print(up_line_tail);

  # for y in range(len(txt2)):
  #   n = (len(txt2[y])-2);
  #   for a1 in range(len(txt2[y])):
  #     if (txt2[y][n] == ' '):
  #       n=n-1;
  #     else:
  #       low_line_tail[y]=n;
  #       n=0;
  #       break;
  # print(low_line_tail);

def cmpr2(txt,Allen_list):
  # T = txt.readlines();

  # T_lines_num = len(T);

  up_line_head=np.zeros(shape=(len(txt),1));
  up_line_tail=np.zeros(shape=(len(txt),1));
 
  # low_line_head=np.zeros(shape=(len(txt1),1));
  # low_line_tail=np.zeros(shape=(len(txt1),1));
  # print(len(txt[1]));
  n=0;
  for x in range(len(txt)):
    for l in txt[x]:
      if (l == ' '):
        n=n+1;
      else:
        up_line_head[x]=n;
        n=0;
        break;
  print(up_line_head);

  for y in range(len(txt)):
    n = (len(txt[y])-2);
    for a1 in range(len(txt[y])):
      if (txt[y][n] == ' '):
        n=n-1;
      else:
        up_line_tail[y]=n;
        n=0;
        break;
  print(up_line_tail);
  cmpr_times = (len(txt)-1);
  
  for i in range(cmpr_times):
    if (up_line_head[i] < up_line_head[i+1] and up_line_tail[i] < up_line_tail[i+1]):
      Allen_list.append(-4);
      print('type1');
    if (up_line_head[i] > up_line_head[i+1] and up_line_tail[i] > up_line_tail[i+1]):
      Allen_list.append(4);      
      print('type2');
    if (up_line_head[i] == up_line_head[i+1] and up_line_tail[i] == up_line_tail[i+1]):
      Allen_list.append(0);
      print('type3');
    if (up_line_head[i] < up_line_head[i+1] and up_line_tail[i] < up_line_tail[i+1] and up_line_tail[i] < up_line_head[i+1]):
      Allen_list.append(-6);
      print('type4');
    if (up_line_head[i] > up_line_head[i+1] and up_line_tail[i] > up_line_tail[i+1] and up_line_head[i] > up_line_tail[i+1]):
      Allen_list.append(6);
      print('type5');
    if (up_line_head[i] == up_line_head[i+1] and up_line_tail[i] < up_line_tail[i+1]):
      Allen_list.append(-2);
      print('type6');
    if (up_line_head[i] == up_line_head[i+1] and up_line_tail[i] > up_line_tail[i+1]):
      Allen_list.append(2);
      print('type7');
    if (up_line_head[i] < up_line_head[i+1] and up_line_tail[i] == up_line_tail[i+1]):
      Allen_list.append(-3);
      print('type8');
    if (up_line_head[i] > up_line_head[i+1] and up_line_tail[i] == up_line_tail[i+1]):
      Allen_list.append(3);
      print('type9');
    if (up_line_head[i] > up_line_head[i+1] and up_line_tail[i] < up_line_tail[i+1]):
      Allen_list.append(-1);
      print('type10');
    if (up_line_head[i] < up_line_head[i+1] and up_line_tail[i] > up_line_tail[i+1]):
      Allen_list.append(1);
      print('type11');
    if (up_line_head[i] < up_line_head[i+1] and up_line_tail[i] < up_line_tail[i+1] and up_line_tail[i] == up_line_head[i+1]):
      Allen_list.append(-5);
      print('type12');
    if (up_line_head[i] > up_line_head[i+1] and up_line_tail[i] > up_line_tail[i+1] and up_line_head[i] == up_line_tail[i+1]):
      Allen_list.append(5);
      print('type13');
  
cmpr2(txt1,a1);
print(a1[0]);
cmpr2(txt2,a2);
print(a2[0]);


def cal_smlr(t1,t2):
  smLr = 1;
  for i in range(len(t1)):
    dist = abs(t1[i] - t2[i]);
    smLr = smLr*(1-dist*0.05);
  return smLr;

print (cal_smlr(a1,a2));

<p>
This is an HTML paragraph.
</p>

[[0.]
 [3.]]
[[ 6.]
 [13.]]
type1
-4
[[3.]
 [0.]]
[[ 9.]
 [12.]]
type10
-1
0.85
